include: "rules/common.smk"
include: "rules/setup.smk"
include: "rules/smoove.smk"
include: "rules/mosdepth.smk"


rule sv_calling:
    output:
        vep_annotated="data/sv_variants/smoove/vep/annotated.vcf.gz",
        mosdepth="reports/multiqc/mosdepth/report.html",
