samples: "config/samples.tsv"
#bam_folder: "resources/BAM"
variants_folder: "data/sv_variants"

#dummy_header: "resources/dummy_header.vcf"
ref_genome_accession: "GCF_964237555.1"
ref_genome_name: "mOryCun1.1"
ref_genome: "resources/ref_genome/GCF_964237555.1_mOryCun1.1_genomic.fna.gz"
ref_genome_fai: "resources/ref_genome/GCF_964237555.1_mOryCun1.1_genomic.fna.gz.fai"
ref_genome_gff: "resources/ref_genome/GCF_964237555.1_mOryCun1.1_genomic.gff.gz"
ref_genome_gff_csi: "resources/ref_genome/GCF_964237555.1_mOryCun1.1_genomic.gff.gz.csi"

vep_use_gff: False

ensembl_ref:
  # ensembl species name
  species: oryctolagus_cuniculus
  # ensembl release
  release: 112
  # genome build
  build: OryCun2.0

vep_cache_dir: /lustre/home/bolner/RESOURCES/VEP_CACHE/oryctolagus_cuniculus/
vep_plugins_dir: /lustre/home/bolner/RESOURCES/VEP_CACHE/oryctolagus_cuniculus/
